required = ["github.com/GeertJohan/go.rice", "golang.org/x/tools/cmd/stringer", "github.com/GeertJohan/go.rice/rice", "github.com/golang/protobuf/protoc-gen-go", "github.com/golang/protobuf/ptypes/empty", "github.com/golang/mock/gomock", "github.com/golang/mock/mockgen", "golang.org/x/tools/cmd/cover", "golang.org/x/lint/golint", "github.com/tebeka/go2xunit", "github.com/kisielk/errcheck", "github.com/dlespiau/covertool", "github.com/libvirt/libvirt-go", "github.com/libvirt/libvirt-go-xml", "github.com/gregoryv/gocyclo"]

[[override]]
  version = "=v1.7.1"
  name = "github.com/deckarep/golang-set"

[[override]]
  name = "github.com/aws/aws-sdk-go"
  version = "=v1.20.12"

#[[override]]
#  name = "github.com/Azure/azure-sdk-for-go"
#  version = "=v31.1.0"

[[constraint]]
  name = "github.com/coreos/go-oidc"
  version = "=2.0.0"

[[constraint]]
  name = "github.com/gobwas/glob"
  version = "=v0.2.3"

[[override]]
  name = "github.com/golang/protobuf"
  version = "=v1.2.0"

[[override]]
  name = "go.opencensus.io"
  revision = "9c377598961b706d1542bd2d84d538b5094d596e"

[[override]]
  name = "google.golang.org/genproto"
  revision = "e7d98fc518a78c9f8b5ee77be7b0b317475d89e1"

[[override]]
  name = "github.com/gophercloud/gophercloud"
  revision = "7892efa714f10951c5483a28c7471d8051b12975"

#  branch = "master"
# source = "github.com/oscarpicas/gophercloud.git"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "=1.4.0"

[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "=v1.9.1"

[[constraint]]
  name = "github.com/davecgh/go-spew"
  version = "=v1.1.1"

[[override]]
  name = "github.com/mjibson/go-dsp"
  revision = "11479a337f1259210b7c8f93f7bf2b0cc87b066e"

[[override]]
  name = "github.com/pengux/check"
  revision = "53861b30913dfdf93e58e4379d510eba93261097"

[[override]]
  name = "github.com/satori/go.uuid"
  revision = "36e9d2ebbde5e3f13ab2e25625fd453271d6522e"

[[constraint]]
  name = "github.com/sethvargo/go-password"
  version = "=v0.1.1"

[[override]]
  name = "github.com/spf13/viper"
  version = "=v1.2.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "=v1.2.2"

[[override]]
  name = "github.com/urfave/cli"
  version = "=v1.20.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "=v1.3.0"

[[override]]
  name = "github.com/nanobox-io/golang-scribble"
  revision = "aa3e7c118975babb5ab3bc2a221b9d5a420b625b"

[[override]]
  name = "golang.org/x/crypto"
  revision = "0e37d006457bf46f9e6692014ba72ef82c33022c"

[[override]]
  name = "golang.org/x/net"
  revision = "4dfa2610cdf3b287375bbba5b8f2a14d3b01d8de"

[[override]]
  name = "golang.org/x/oauth2"
  revision = "d2e6202438beef2727060aa7cabdd924d92ebfd9"

[[override]]
  name = "google.golang.org/grpc"
  version = "=v1.15.0"

[[constraint]]
  name = "github.com/dlespiau/covertool"
  revision = "b0c4c6d0583aae4e3b5d12b6ec47767670548cc4"

[[constraint]]
  name = "github.com/graymeta/stow"
  branch = "master"
  source = "github.com/appscode/stow.git"

[[constraint]]
  name = "github.com/xrash/smetrics"
  revision = "a3153f7040e90324c58c6287535e26a0ac5c1cc1"

[[constraint]]
  name = "github.com/asaskevich/govalidator"
  version = "=v9"

[[override]]
  name = "github.com/libvirt/libvirt-go"
  version = "=v4.8.0"

[[override]]
  name = "github.com/libvirt/libvirt-go-xml"
  version = "=v4.8.0"

[[override]]
  name = "github.com/klauspost/reedsolomon"
  version = "=v1.9.1"

[[override]]
  name = "github.com/ovh/go-ovh"
  revision = "ba5adb4cf0148a3dbdbd30586f075266256a77b1"

[[override]]
  name = "github.com/denisbrodbeck/machineid"

[prune]
  go-tests = true
