name: MacOs Latest Go Build CI

on:
  push:
    branches:
      - master
      - develop
      - hotfixes
      - 'feature/**'
      - 'release/**'
  pull_request:
    branches:
      - master
      - develop
      - 'release/**'

env:
  GOVERSION: '1.17.7' # The Go version to download (if necessary) and use.
  PROTOCVERSION: 3.17.3

jobs:

  build-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ${{env.GOVERSION}}
    - name: Install Protoc
      run: |
        brew update
        brew install protoc-gen-go

    - run: make ci
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: macos-artefacts
        path: |
          generation_results.log
          vet_results.log
          test_results.log
          style_results.log
          go.mod
          go.sum
