name: Go Build CI

on:
  push:
    branches: [ bugfix/develop ]
  pull_request:
    branches: [ bugfix/develop ]

env:
  GOVERSION: '1.16.8' # The Go version to download (if necessary) and use.
  PROTOCVERSION: 3.17.3

jobs:

  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ${{env.GOVERSION}}
    - name: Install Protoc
      run: |
        cd /tmp
        PROTOCZIP=$(echo "protoc-${{env.PROTOCVERSION}}-$(uname -s | tr '[:upper:]' '[:lower:]')-$(uname -m).zip")
        wget https://github.com/google/protobuf/releases/download/v${{env.PROTOCVERSION}}/$PROTOCZIP
        sudo unzip -d /opt/protoc $PROTOCZIP
        sudo chmod a+r -R /opt/protoc
        sudo chmod a+xr /opt/protoc/bin/protoc
        sudo ln -s /opt/protoc/bin/protoc /usr/local/bin/
    - run: make all
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: linux-artefacts
        path: |
          generation_results.log
          vet_results.log
          test_results.log
          go.mod
          go.sum

  build-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ${{env.GOVERSION}}
    - name: Install Protoc
      run: |
        brew update
        brew install protoc-gen-go

    - run: make all
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: macos-artefacts
        path: |
          generation_results.log
          vet_results.log
          test_results.log
          go.mod
          go.sum